backend:
  name: git-gateway
  branch: master # Change to 'master' if your main git branch is called master

media_folder: "img" # Folder where uploaded images are saved
public_folder: "img" # How images are referenced in your code

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Page Content", name: "body", widget: "markdown"}